print_freq: 1
verbose: False
num_classes: 100
model : 
  name: 'cvt'
  architecture: 'cvt_13_224'
loss:
  loss: 'softmax'
  label_smoothing: 0.1
amp: True
train:
  image_size: [224, 224]
  batch_size: 64
  begin_epoch: 0
  epochs: 300
  optimizer: 'adamW'
  optimizer_args:
    lr: 0.00025
  lr: 0.00025
  weight_decay: 0.05
  without_weight_decay_list: ['bn', 'bias', 'ln']
  clip_grad_norm: 0.0
  shuffle: true
  scheduler: 
    method: 'timm'
    args:
      sched: 'cosine'
      warmup_epochs: 5
      warmup_lr: 0.000001
      min_lr: 0.00001
      cooldown_epochs: 10
      decay_rate: 0.1
  save_dir: 'test1'
  save_epoch_models: True
test:
  batch_size: 32
  image_size: [224, 224]
  interpolation: 3
  center_crop: true
aug:
  scale: [0.08, 1.0]
  ratio: [0.75, 1.333333]
  mixup_prob: 1.0
  mixup_switch_prob: 0.5
  mixup_mode: 'batch'
  mixup: 0.8
  mixcut: 1.0
  interpolation: 2
  timm_aug:
    use_loader: True
    re_count: 1
    re_mode: pixel
    re_split: false
    re_prob: 0.25
    auto_augment: rand-m9-mstd0.5-inc1
    hflip: 0.5
    vflip: 0.0
    color_jitter: 0.4
    interpolation: bicubic
input:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]