print_freq: 1
verbose: False
num_classes: 100
amp: False
use_amp: False
image_size: [224, 224]
model: 
  name: 'convnextv2'
  architecture: 'convnextv2_tiny'
train:
  batch_size: 128
  lr: 0.0004
  warmup_epochs: 20
  warmup_lr: 0.000001
  min_lr: 0.00001
  cooldown_epochs: 10
  begin_epoch: 20
  epochs: 300
  warmup_epochs: 20
  weight_decay: 0.05
  layer_decay: 0.9
  layer_decay_type: 'single'
  clip_grad: 0.0
  optimizer:
    name: 'adamw'
    momentum: 0.9
    eps: 0.00000001
    betas: [0.9, 0.999]
  scheduler: 
    method: 'timm'
    args:
      sched: 'cosine'
      warmup_epochs: 20
      warmup_lr: 0.000001
      min_lr: 0.00001
      cooldown_epochs: 10
      decay_rate: 0.1
  aug:
    color_jitter: 0.4
    aa: 'rand-m9-mstd0.5-inc1'
    train_interpolation: 'bicubic'
    drop_path: 0.2
    reprob: 0.25
    remode: 'pixel'
    recount: 1
    mixup: 0.8
    mixup_prob: 1.0
    mixup_switch_prob: 0.5
    mixup_mode: 'batch'
    cutmix: 1.0
    cutmix_minmax: None
    smoothing: 0.1
  save_dir: 'test1'
  save_epoch_models: True
test:
  crop_pct: None
