_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 41
                - 49
                - 55
                - 63
            "2":
                - 1
                - 41
                - 49
                - 55
                - 63
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.7
            "8":
                - 2
                - 5
            "12": 0.18.7
            "13": linux-x86_64
amp:
    value: true
aug:
    value:
        interpolation: 2
        mixcut: 1
        mixup: 0.8
        mixup_mode: batch
        mixup_prob: 1
        mixup_switch_prob: 0.5
        ratio: (3.0/4.0, 4.0/3.0)
        scale: (0.08, 1.0)
        timm_aug:
            auto_augment: rand-m9-mstd0.5-inc1
            color_jitter: 0.4
            hflip: 0.5
            interpolation: bicubic
            re_count: 1
            re_mode: pixel
            re_prob: 0.25
            re_split: false
            use_loader: true
            vflip: 0
input:
    value:
        mean:
            - 0.485
            - 0.456
            - 0.406
        std:
            - 0.229
            - 0.224
            - 0.225
loss:
    value:
        label_smoothing: 0.1
        loss: softmax
model:
    value:
        architecture: cvt_13_224
        name: cvt
num_classes:
    value: 100
print_freq:
    value: 1
test:
    value:
        batch_size: 32
        center_crop: true
        image_size:
            - 224
            - 224
        interpolation: 3
train:
    value:
        batch_size: 256
        begin_epoch: 0
        clip_grad_norm: 0
        epochs: 300
        image_size:
            - 224
            - 224
        lr: 0.001
        optimizer: adamW
        optimizer_args:
            lr: 0.001
        save_dir: test1
        save_epoch_models: true
        scheduler:
            args:
                cooldown_epochs: 10
                decay_rate: 0.1
                min_lr: 1e-05
                sched: cosine
                warmup_epochs: 5
                warmup_lr: 1e-06
            method: timm
        shuffle: true
        weight_decay: 0.05
        without_weight_decay_list:
            - bn
            - bias
            - ln
verbose:
    value: false
