model : 
  name: 'swinv2_tiny_patch_window8_256'
loss:
  loss: 'softmax'
  label_smoothing: 0.1
amp: True
train:
  image_size: [224, 224]
  batch_size: 256
  begin_epoch: 0
  epochs: 300
  optimizer: 'adamW'
  weight_decay: 0.05
  without_weight_decay_list: ['bn', 'bias', 'ln']
  shuffle: true
  scheduler: 
    method: 'timm'
    args:
      sched: 'cosine'
      warmup_epochs: 5
      warmup_lr: 0.000001
      min_lr: 0.00001
      cooldown_epochs: 10
      decay_rate: 0.1
  save_dir: 'test1'
  save_epoch_models: True
test:
  batch_size: 32
  image_size: [224, 224]
  interpolation: 3
  center_crop: true
aug:
  scale: (0.08, 1.0)
  ratio: (3.0/4.0, 4.0/3.0)
  mixup_prob: 1.0
  mixup: 0.8
  mixcut: 1.0
  timm_aug:
    use_loader: True
    re_count: 1
    re_mode: pixel
    re_split: false
    re_prob: 0.25
    auto_augment: rand-m9-mstd0.5-inc1
    hflip: 0.5
    vflip: 0.0
    color_jitter: 0.4
    interpolation: bicubic
input:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]